# This workflow will build a MuleSoft project and deploy to CloudHub

name: Cloudhub deployment with Maven [PROD]

on:
  push:
    branches: [ main ]
	
env:
  GLOBAL_MULESOFT_CICD_CLIENT_ID : ${{ secrets.appClientId }}
  GLOBAL_MULESOFT_CICD_CLIENT_SECRET : ${{ secrets.appClientSecret }}
    
jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Deploy with Maven
      run: mvn clean deploy -DmuleDeploy -Dmule.environment="Production" -Dmule.target="api-testSpace" -Dmule.appClientId=GLOBAL_MULESOFT_CICD_CLIENT_ID -Dmule.appClientSecret=GLOBAL_MULESOFT_CICD_CLIENT_SECRET -Dmule.grantType="client_credentials" -Dproject.name="mule-cicd2" -DappTag="prod" -Dmule.replicas="1" -Dmule.vCores="0.1"